name: Publish Python distribution to PyPI and TestPyPI
on: push
 
jobs:
  build-n-publish:
    name: Publish Python distribution
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.testpypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        #if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}